nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Origin', 'X-Requested-With', 'Content-Type','Content-disposition', 'Accept', 'Authorization','Cookies','tokenview','nocache']
        expose_headers: ['content-disposition','Content-Type']
        max_age: 3600
    paths:
        '^/':
            allow_headers: ['Origin', 'X-Requested-With', 'Content-Type','Content-disposition', 'Accept', 'Authorization','Cookies','tokenview','nocache']
            expose_headers: ['content-disposition','Content-Type']
