controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
# config/routes.yaml
gesdinet_jwt_refresh_token:
    path: /api/token/refresh
    controller: gesdinet.jwtrefreshtoken::refresh

app_reset_password:
    path: /reset/password
    controller: App\Controller\FormResetPasswordController::formsPassword
    